---
- name: Get the Private Automation Hub Token
  hosts: all
  connection: local
  vars_files:
    - ../vars/secrets.yml

  tasks:
    # probably not good but kinda works, looking for better solutions,
    # you are better off removing this block and getting token into vault by hand
    - name: Figuring out AH token
      when: ah_token is not defined or ah_token['token'] is defined
      block:
        - name: Authenticate and get an API token from Automation Hub
          register: r_ah_token
          infra.ah_configuration.ah_token:
            ah_host: https://aap.kona.services:8444
            ah_username: "{{ ah_token_username | default('admin') }}"
            ah_password: "{{ ah_token_password }}"
            ah_path_prefix: galaxy # this is for private automation hub
            validate_certs: false

        - name: Fixing format
          when: r_ah_token['changed'] # noqa: no-handler
          ansible.builtin.set_fact:
            ah_token: "{{ ah_token['token'] }}"

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch